apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dev
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-storage
  volumeName: pv-dev