apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  template:
    spec:
      containers:
        - name: springboot
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/findb-dev?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8"
